[2025-05-09T17:30:50.991+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T17:25:12.663470+00:00 [queued]>
[2025-05-09T17:30:51.004+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T17:25:12.663470+00:00 [queued]>
[2025-05-09T17:30:51.005+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-09T17:30:51.020+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_hive_command> on 2025-05-09 17:25:12.663470+00:00
[2025-05-09T17:30:51.026+0000] {standard_task_runner.py:57} INFO - Started process 3853 to run task
[2025-05-09T17:30:51.030+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_hive_command', 'manual__2025-05-09T17:25:12.663470+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmps8_stosc']
[2025-05-09T17:30:51.032+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask run_hive_command
[2025-05-09T17:30:51.079+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T17:25:12.663470+00:00 [running]> on host d4afc872a8aa
[2025-05-09T17:30:51.184+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_hive_command' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T17:25:12.663470+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T17:25:12.663470+00:00'
[2025-05-09T17:30:51.185+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-09T17:30:51.187+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec hive hive -f query.hql']
[2025-05-09T17:30:51.199+0000] {subprocess.py:86} INFO - Output:
[2025-05-09T17:30:53.136+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-05-09T17:30:53.141+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-05-09T17:30:53.142+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.4/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-05-09T17:30:53.143+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-05-09T17:30:53.144+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-05-09T17:30:54.553+0000] {subprocess.py:93} INFO - 
[2025-05-09T17:30:54.554+0000] {subprocess.py:93} INFO - Logging initialized using configuration in file:/opt/hive/conf/hive-log4j2.properties Async: true
[2025-05-09T17:31:25.511+0000] {subprocess.py:93} INFO - FAILED: SemanticException org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
[2025-05-09T17:32:15.489+0000] {subprocess.py:97} INFO - Command exited with return code 64
[2025-05-09T17:32:15.512+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 64.
[2025-05-09T17:32:15.520+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_hive_command, execution_date=20250509T172512, start_date=20250509T173050, end_date=20250509T173215
[2025-05-09T17:32:15.561+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 69 for task run_hive_command (Bash command failed. The command returned a non-zero exit code 64.; 3853)
[2025-05-09T17:32:15.588+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-09T17:32:15.619+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
