[2025-05-23T09:28:47.115+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T09:28:47.134+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T09:28:47.134+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-23T09:28:47.176+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_superset_dashboard> on 2025-05-22 00:00:00+00:00
[2025-05-23T09:28:47.201+0000] {standard_task_runner.py:57} INFO - Started process 720 to run task
[2025-05-23T09:28:47.249+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_superset_dashboard', 'scheduled__2025-05-22T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpwfkrmpti']
[2025-05-23T09:28:47.267+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask run_superset_dashboard
[2025-05-23T09:28:47.446+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard scheduled__2025-05-22T00:00:00+00:00 [running]> on host 6c702459c558
[2025-05-23T09:28:47.768+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_superset_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T00:00:00+00:00'
[2025-05-23T09:28:47.769+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-23T09:28:47.770+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec superset python /app/dashboard/step1_connection_db.py && docker exec superset python /app/dashboard/step2_creation_of_datasets.py && docker exec superset python /app/dashboard/step3_create_charts.py && docker exec superset python step4_create_dashbord.py']
[2025-05-23T09:28:47.786+0000] {subprocess.py:86} INFO - Output:
[2025-05-23T09:29:01.228+0000] {subprocess.py:93} INFO - ‚úÖ Login successful.
[2025-05-23T09:29:01.229+0000] {subprocess.py:93} INFO - Access Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNzQ3OTkyNTMwLCJqdGkiOiI5YjljNGI1Yi1iZGZjLTRjOTctYWYxZS1hOTRkYjEzOWVkYmMiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE3NDc5OTI1MzAsImNzcmYiOiI0ZGI0MDE1YS1jNDdmLTRlMWMtODFkMy02YWVhNmRmYmI4YmYiLCJleHAiOjE3NDc5OTM0MzB9.bAJm1tj4HJrvMxfaBog8A21B0OB5umbrCH7Nw2sdlas
[2025-05-23T09:29:01.229+0000] {subprocess.py:93} INFO - ‚úÖ CSRF token received:
[2025-05-23T09:29:01.230+0000] {subprocess.py:93} INFO - IjIyNWUyM2Q5M2UzZTQzMjA4MDFhMzRkZDA1NjQ1MTFhOGQzZmQyYTYi.aDA_0w.OaWV-dk8ft_VYDJNLKj6TSMmSbg
[2025-05-23T09:29:01.230+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:29:01.230+0000] {subprocess.py:93} INFO - Response: {"message":{"database_name":"A database with the same name already exists."}}
[2025-05-23T09:29:01.231+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:29:59.367+0000] {subprocess.py:93} INFO - ‚úÖ Logged in successfully
[2025-05-23T09:29:59.368+0000] {subprocess.py:93} INFO - ‚úÖ CSRF token retrieved
[2025-05-23T09:29:59.369+0000] {subprocess.py:93} INFO - ‚úÖ Hive Warehouse database ID: 1
[2025-05-23T09:29:59.369+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Distribution%20of%20Payment%20Methods already exists"]}}
[2025-05-23T09:29:59.370+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:29:59.370+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:29:59.371+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Transaction%20Volume%20by%20Device%20Type already exists"]}}
[2025-05-23T09:29:59.371+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:29:59.371+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:29:59.372+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":"Fatal error"}
[2025-05-23T09:29:59.372+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:29:59.372+0000] {subprocess.py:93} INFO - Status: 500
[2025-05-23T09:29:59.373+0000] {subprocess.py:93} INFO - ‚úÖ Dataset 'Number of Transactions by Month' created successfully. ID: 4
[2025-05-23T09:29:59.373+0000] {subprocess.py:93} INFO - ‚úÖ Dataset 'Proportion of Fraudulent Transactions' created successfully. ID: 5
[2025-05-23T09:29:59.373+0000] {subprocess.py:93} INFO - ‚úÖ Dataset 'Total Transaction Amount by Product Category' created successfully. ID: 6
[2025-05-23T09:30:06.227+0000] {subprocess.py:93} INFO - üîê Authenticating with Superset...
[2025-05-23T09:30:06.227+0000] {subprocess.py:93} INFO - ‚úÖ Authentication successful
[2025-05-23T09:30:06.228+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:30:06.228+0000] {subprocess.py:93} INFO - üöÄ Starting dashboard creation process...
[2025-05-23T09:30:06.229+0000] {subprocess.py:93} INFO - üìä Charts to create: 6
[2025-05-23T09:30:06.229+0000] {subprocess.py:93} INFO - üèóÔ∏è Dashboard name: Transaction Analytics Dashboard
[2025-05-23T09:30:06.230+0000] {subprocess.py:93} INFO - ==================================================
[2025-05-23T09:30:06.230+0000] {subprocess.py:93} INFO - üìä Creating chart: Fraud Detection Overview
[2025-05-23T09:30:06.231+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Fraud Detection Overview' created (ID: 3)
[2025-05-23T09:30:06.231+0000] {subprocess.py:93} INFO - üìä Creating chart: Number of Transactions by Month
[2025-05-23T09:30:06.231+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Number of Transactions by Month' created (ID: 6)
[2025-05-23T09:30:06.232+0000] {subprocess.py:93} INFO - üìä Creating chart: Average Transaction Amount by Age Group
[2025-05-23T09:30:06.232+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Average Transaction Amount by Age Group' created (ID: 9)
[2025-05-23T09:30:06.232+0000] {subprocess.py:93} INFO - üìä Creating chart: Distribution of Payment Methods
[2025-05-23T09:30:06.233+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Distribution of Payment Methods' created (ID: 11)
[2025-05-23T09:30:06.233+0000] {subprocess.py:93} INFO - üìä Creating chart: Transaction Volume by Device Type
[2025-05-23T09:30:06.233+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Transaction Volume by Device Type' created (ID: 13)
[2025-05-23T09:30:06.234+0000] {subprocess.py:93} INFO - üìä Creating chart: Revenue by Product Category
[2025-05-23T09:30:06.234+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Revenue by Product Category' created (ID: 15)
[2025-05-23T09:30:06.235+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:30:06.235+0000] {subprocess.py:93} INFO - üìà Successfully created 6 out of 6 charts
[2025-05-23T09:30:06.332+0000] {subprocess.py:93} INFO - python: can't open file '/app/step4_create_dashbord.py': [Errno 2] No such file or directory
[2025-05-23T09:30:06.341+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-23T09:30:06.354+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-23T09:30:06.357+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_superset_dashboard, execution_date=20250522T000000, start_date=20250523T092847, end_date=20250523T093006
[2025-05-23T09:30:06.372+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task run_superset_dashboard (Bash command failed. The command returned a non-zero exit code 2.; 720)
[2025-05-23T09:30:06.411+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-23T09:30:06.446+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
