[2025-05-23T09:35:07.840+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T09:35:07.849+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T09:35:07.850+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-23T09:35:07.864+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_superset_dashboard> on 2025-05-22 00:00:00+00:00
[2025-05-23T09:35:07.871+0000] {standard_task_runner.py:57} INFO - Started process 884 to run task
[2025-05-23T09:35:07.875+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_superset_dashboard', 'scheduled__2025-05-22T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpz35n6kg8']
[2025-05-23T09:35:07.880+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask run_superset_dashboard
[2025-05-23T09:35:07.936+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard scheduled__2025-05-22T00:00:00+00:00 [running]> on host 6c702459c558
[2025-05-23T09:35:08.184+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_superset_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T00:00:00+00:00'
[2025-05-23T09:35:08.185+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-23T09:35:08.187+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec superset python /app/dashboard/step1_connection_db.py && docker exec superset python /app/dashboard/step2_creation_of_datasets.py && docker exec superset python /app/dashboard/step3_create_charts.py && docker exec superset python step4_create_dashbord.py']
[2025-05-23T09:35:08.202+0000] {subprocess.py:86} INFO - Output:
[2025-05-23T09:35:08.635+0000] {subprocess.py:93} INFO - ‚úÖ Login successful.
[2025-05-23T09:35:08.636+0000] {subprocess.py:93} INFO - Access Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNzQ3OTkyOTA4LCJqdGkiOiJlZGUxNWNhMC0zYzg0LTRkZGQtYjU2Yi1lZDU3ODE2OTY1ZjgiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE3NDc5OTI5MDgsImNzcmYiOiJhZmYzZjRhYS0wNDBiLTQ1MTQtOWIxMi01ZmI1YTgwNDcwNmIiLCJleHAiOjE3NDc5OTM4MDh9.R81O6963yf9Ag1gGPuIPkrKlRAfjQ7LlI0yrDkWS0d0
[2025-05-23T09:35:08.637+0000] {subprocess.py:93} INFO - ‚úÖ CSRF token received:
[2025-05-23T09:35:08.638+0000] {subprocess.py:93} INFO - ImIxZGJhYjg4NzBkNTdhYTlhMjhlMDg0Njc1ZDFhYTA0ZWM0Zjg5Nzgi.aDBBTA.rOe0aYvNi5huyp_czXDyAKYwr6A
[2025-05-23T09:35:08.638+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:35:08.639+0000] {subprocess.py:93} INFO - Response: {"message":{"database_name":"A database with the same name already exists."}}
[2025-05-23T09:35:08.640+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:35:09.359+0000] {subprocess.py:93} INFO - ‚úÖ Logged in successfully
[2025-05-23T09:35:09.359+0000] {subprocess.py:93} INFO - ‚úÖ CSRF token retrieved
[2025-05-23T09:35:09.360+0000] {subprocess.py:93} INFO - ‚úÖ Hive Warehouse database ID: 1
[2025-05-23T09:35:09.360+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Distribution%20of%20Payment%20Methods already exists"]}}
[2025-05-23T09:35:09.361+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:35:09.361+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:35:09.361+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Transaction%20Volume%20by%20Device%20Type already exists"]}}
[2025-05-23T09:35:09.362+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:35:09.362+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:35:09.363+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Average%20Transaction%20Amount%20by%20Customer%20Age%20Group already exists"]}}
[2025-05-23T09:35:09.363+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:35:09.363+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:35:09.363+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Number%20of%20Transactions%20by%20Month already exists"]}}
[2025-05-23T09:35:09.364+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:35:09.364+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:35:09.364+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Proportion%20of%20Fraudulent%20Transactions already exists"]}}
[2025-05-23T09:35:09.364+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:35:09.365+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:35:09.365+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Total%20Transaction%20Amount%20by%20Product%20Category already exists"]}}
[2025-05-23T09:35:09.365+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:35:09.366+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:35:16.510+0000] {subprocess.py:93} INFO - üîê Authenticating with Superset...
[2025-05-23T09:35:16.511+0000] {subprocess.py:93} INFO - ‚úÖ Authentication successful
[2025-05-23T09:35:16.511+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:35:16.511+0000] {subprocess.py:93} INFO - üöÄ Starting dashboard creation process...
[2025-05-23T09:35:16.512+0000] {subprocess.py:93} INFO - üìä Charts to create: 6
[2025-05-23T09:35:16.512+0000] {subprocess.py:93} INFO - üèóÔ∏è Dashboard name: Transaction Analytics Dashboard
[2025-05-23T09:35:16.512+0000] {subprocess.py:93} INFO - ==================================================
[2025-05-23T09:35:16.513+0000] {subprocess.py:93} INFO - üìä Creating chart: Fraud Detection Overview
[2025-05-23T09:35:16.513+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Fraud Detection Overview' created (ID: 17)
[2025-05-23T09:35:16.513+0000] {subprocess.py:93} INFO - üìä Creating chart: Number of Transactions by Month
[2025-05-23T09:35:16.514+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Number of Transactions by Month' created (ID: 18)
[2025-05-23T09:35:16.514+0000] {subprocess.py:93} INFO - üìä Creating chart: Average Transaction Amount by Age Group
[2025-05-23T09:35:16.514+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Average Transaction Amount by Age Group' created (ID: 20)
[2025-05-23T09:35:16.514+0000] {subprocess.py:93} INFO - üìä Creating chart: Distribution of Payment Methods
[2025-05-23T09:35:16.515+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Distribution of Payment Methods' created (ID: 23)
[2025-05-23T09:35:16.515+0000] {subprocess.py:93} INFO - üìä Creating chart: Transaction Volume by Device Type
[2025-05-23T09:35:16.515+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Transaction Volume by Device Type' created (ID: 25)
[2025-05-23T09:35:16.515+0000] {subprocess.py:93} INFO - üìä Creating chart: Revenue by Product Category
[2025-05-23T09:35:16.516+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Revenue by Product Category' created (ID: 27)
[2025-05-23T09:35:16.516+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:35:16.516+0000] {subprocess.py:93} INFO - üìà Successfully created 6 out of 6 charts
[2025-05-23T09:35:16.614+0000] {subprocess.py:93} INFO - python: can't open file '/app/step4_create_dashbord.py': [Errno 2] No such file or directory
[2025-05-23T09:35:16.624+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-23T09:35:16.636+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-23T09:35:16.640+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_superset_dashboard, execution_date=20250522T000000, start_date=20250523T093507, end_date=20250523T093516
[2025-05-23T09:35:16.654+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task run_superset_dashboard (Bash command failed. The command returned a non-zero exit code 2.; 884)
[2025-05-23T09:35:16.676+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-23T09:35:16.700+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
