[2025-05-09T17:44:36.945+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T17:38:07.153488+00:00 [queued]>
[2025-05-09T17:44:36.962+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T17:38:07.153488+00:00 [queued]>
[2025-05-09T17:44:36.963+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-09T17:44:36.992+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_hive_command> on 2025-05-09 17:38:07.153488+00:00
[2025-05-09T17:44:37.004+0000] {standard_task_runner.py:57} INFO - Started process 4336 to run task
[2025-05-09T17:44:37.009+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_hive_command', 'manual__2025-05-09T17:38:07.153488+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmpd5o7k7v1']
[2025-05-09T17:44:37.012+0000] {standard_task_runner.py:85} INFO - Job 78: Subtask run_hive_command
[2025-05-09T17:44:37.066+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T17:38:07.153488+00:00 [running]> on host d4afc872a8aa
[2025-05-09T17:44:37.151+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_hive_command' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T17:38:07.153488+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T17:38:07.153488+00:00'
[2025-05-09T17:44:37.153+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-09T17:44:37.155+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'command1 && command2 && docker exec hive hive -f query.hql']
[2025-05-09T17:44:37.166+0000] {subprocess.py:86} INFO - Output:
[2025-05-09T17:44:37.167+0000] {subprocess.py:93} INFO - /bin/bash: line 1: command1: command not found
[2025-05-09T17:44:37.168+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-09T17:44:37.180+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-09T17:44:37.184+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_hive_command, execution_date=20250509T173807, start_date=20250509T174436, end_date=20250509T174437
[2025-05-09T17:44:37.203+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 78 for task run_hive_command (Bash command failed. The command returned a non-zero exit code 127.; 4336)
[2025-05-09T17:44:37.224+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-09T17:44:37.246+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
