[2025-05-09T18:37:48.592+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T18:31:52.240044+00:00 [queued]>
[2025-05-09T18:37:48.603+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T18:31:52.240044+00:00 [queued]>
[2025-05-09T18:37:48.603+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-09T18:37:48.621+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_hive_command> on 2025-05-09 18:31:52.240044+00:00
[2025-05-09T18:37:48.638+0000] {standard_task_runner.py:57} INFO - Started process 6304 to run task
[2025-05-09T18:37:48.641+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_hive_command', 'manual__2025-05-09T18:31:52.240044+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmpjghoy73i']
[2025-05-09T18:37:48.644+0000] {standard_task_runner.py:85} INFO - Job 110: Subtask run_hive_command
[2025-05-09T18:37:48.704+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T18:31:52.240044+00:00 [running]> on host d4afc872a8aa
[2025-05-09T18:37:48.811+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_hive_command' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T18:31:52.240044+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T18:31:52.240044+00:00'
[2025-05-09T18:37:48.814+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-09T18:37:48.817+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            # Only create metastore_db if it doesn\'t exist\n            docker exec striming_processing-postgres-1 psql -U *** -d *** -tc "SELECT 1 FROM pg_database WHERE datname = \'metastore_db\'" | grep -q 1 || \\\n            docker exec striming_processing-postgres-1 psql -U *** -d *** -c "CREATE DATABASE metastore_db;" && \\\n\n            # Check if Hive metastore schema already exists\n            docker exec striming_processing-postgres-1 psql -U *** -d metastore_db -tc "SELECT 1 FROM pg_tables WHERE tablename = \'version\'" | grep -q 1 || \\\n            docker exec hive schematool -initSchema -dbType postgres && \\\n\n            # Run Hive script\n            docker exec hive hive -f /home/query.hql\n        ']
[2025-05-09T18:37:48.830+0000] {subprocess.py:86} INFO - Output:
[2025-05-09T18:37:50.912+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-05-09T18:37:50.913+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-05-09T18:37:50.914+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.4/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-05-09T18:37:50.916+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-05-09T18:37:50.920+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-05-09T18:37:52.034+0000] {subprocess.py:93} INFO - Metastore connection URL:	 jdbc:postgresql://postgres:5432/metastore_db
[2025-05-09T18:37:52.035+0000] {subprocess.py:93} INFO - Metastore Connection Driver :	 org.postgresql.Driver
[2025-05-09T18:37:52.036+0000] {subprocess.py:93} INFO - Metastore connection User:	 ***
[2025-05-09T18:37:52.216+0000] {subprocess.py:93} INFO - Starting metastore schema initialization to 2.3.0
[2025-05-09T18:37:52.216+0000] {subprocess.py:93} INFO - Initialization script hive-schema-2.3.0.postgres.sql
[2025-05-09T18:37:52.478+0000] {subprocess.py:93} INFO - Error: ERROR: relation "BUCKETING_COLS" already exists (state=42P07,code=0)
[2025-05-09T18:37:52.478+0000] {subprocess.py:93} INFO - org.apache.hadoop.hive.metastore.HiveMetaException: Schema initialization FAILED! Metastore state would be inconsistent !!
[2025-05-09T18:37:52.479+0000] {subprocess.py:93} INFO - Underlying cause: java.io.IOException : Schema script failed, errorcode 2
[2025-05-09T18:37:52.479+0000] {subprocess.py:93} INFO - Use --verbose for detailed stacktrace.
[2025-05-09T18:37:52.480+0000] {subprocess.py:93} INFO - *** schemaTool failed ***
[2025-05-09T18:37:52.512+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-09T18:37:52.525+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-09T18:37:52.530+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_hive_command, execution_date=20250509T183152, start_date=20250509T183748, end_date=20250509T183752
[2025-05-09T18:37:52.550+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 110 for task run_hive_command (Bash command failed. The command returned a non-zero exit code 1.; 6304)
[2025-05-09T18:37:52.563+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-09T18:37:52.591+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
