[2025-05-23T09:04:00.224+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard manual__2025-05-23T08:57:47.176009+00:00 [queued]>
[2025-05-23T09:04:00.236+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard manual__2025-05-23T08:57:47.176009+00:00 [queued]>
[2025-05-23T09:04:00.237+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-23T09:04:00.258+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_superset_dashboard> on 2025-05-23 08:57:47.176009+00:00
[2025-05-23T09:04:00.265+0000] {standard_task_runner.py:57} INFO - Started process 13381 to run task
[2025-05-23T09:04:00.270+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_superset_dashboard', 'manual__2025-05-23T08:57:47.176009+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpvcv_5d6z']
[2025-05-23T09:04:00.273+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask run_superset_dashboard
[2025-05-23T09:04:00.368+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard manual__2025-05-23T08:57:47.176009+00:00 [running]> on host cb5b79c23ad2
[2025-05-23T09:04:00.695+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_superset_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T08:57:47.176009+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-23T08:57:47.176009+00:00'
[2025-05-23T09:04:00.698+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-23T09:04:00.701+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec superset python /app/dashboard/step1_connection_db.py && docker exec superset python /app/dashboard/step2_creation_of_datasets.py && docker exec superset python /app/dashboard/step3_create_charts.py && docker exec superset python step4_create_dashbord.py']
[2025-05-23T09:04:00.725+0000] {subprocess.py:86} INFO - Output:
[2025-05-23T09:04:01.158+0000] {subprocess.py:93} INFO - ‚úÖ Login successful.
[2025-05-23T09:04:01.160+0000] {subprocess.py:93} INFO - Access Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNzQ3OTkxMDQxLCJqdGkiOiIzNDUyMmRjZS1iNDA2LTRhZWMtOTBiOS02MmM3NzNkODFjYTEiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE3NDc5OTEwNDEsImNzcmYiOiIzODU1Mzk3NS1iOTlmLTQxOGItYmIyNi01MzUzYTllMTBhOGYiLCJleHAiOjE3NDc5OTE5NDF9.hTGrGFfbHNp14Br5Prw3FRpb0vUd-ShrKrrJlfp6Lrk
[2025-05-23T09:04:01.160+0000] {subprocess.py:93} INFO - ‚úÖ CSRF token received:
[2025-05-23T09:04:01.161+0000] {subprocess.py:93} INFO - ImU5NGMyZGZiODFjNGYzOTZkNjMxYjJhZjFmOGFiMzBmMzk0ZDBlYzIi.aDA6AQ.yTDmFjxum2MXoiKnHTS1DhQeiTY
[2025-05-23T09:04:01.161+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:04:01.162+0000] {subprocess.py:93} INFO - Response: {"message":{"database_name":"A database with the same name already exists."}}
[2025-05-23T09:04:01.162+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:04:01.794+0000] {subprocess.py:93} INFO - ‚úÖ Logged in successfully
[2025-05-23T09:04:01.795+0000] {subprocess.py:93} INFO - ‚úÖ CSRF token retrieved
[2025-05-23T09:04:01.796+0000] {subprocess.py:93} INFO - ‚úÖ Hive Warehouse database ID: 1
[2025-05-23T09:04:01.796+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Distribution%20of%20Payment%20Methods already exists"]}}
[2025-05-23T09:04:01.796+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:04:01.797+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:04:01.797+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Transaction%20Volume%20by%20Device%20Type already exists"]}}
[2025-05-23T09:04:01.798+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:04:01.798+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:04:01.798+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Average%20Transaction%20Amount%20by%20Customer%20Age%20Group already exists"]}}
[2025-05-23T09:04:01.799+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:04:01.799+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:04:01.799+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Number%20of%20Transactions%20by%20Month already exists"]}}
[2025-05-23T09:04:01.800+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:04:01.800+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:04:01.800+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Proportion%20of%20Fraudulent%20Transactions already exists"]}}
[2025-05-23T09:04:01.800+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:04:01.801+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:04:01.801+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":{"table":["Dataset default.default.Total%20Transaction%20Amount%20by%20Product%20Category already exists"]}}
[2025-05-23T09:04:01.801+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:04:01.802+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:04:08.752+0000] {subprocess.py:93} INFO - üîê Authenticating with Superset...
[2025-05-23T09:04:08.753+0000] {subprocess.py:93} INFO - ‚úÖ Authentication successful
[2025-05-23T09:04:08.754+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:04:08.754+0000] {subprocess.py:93} INFO - üöÄ Starting dashboard creation process...
[2025-05-23T09:04:08.754+0000] {subprocess.py:93} INFO - üìä Charts to create: 6
[2025-05-23T09:04:08.755+0000] {subprocess.py:93} INFO - üèóÔ∏è Dashboard name: Transaction Analytics Dashboard
[2025-05-23T09:04:08.755+0000] {subprocess.py:93} INFO - ==================================================
[2025-05-23T09:04:08.755+0000] {subprocess.py:93} INFO - üìä Creating chart: Fraud Detection Overview
[2025-05-23T09:04:08.756+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Fraud Detection Overview' created (ID: 19)
[2025-05-23T09:04:08.756+0000] {subprocess.py:93} INFO - üìä Creating chart: Number of Transactions by Month
[2025-05-23T09:04:08.756+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Number of Transactions by Month' created (ID: 20)
[2025-05-23T09:04:08.757+0000] {subprocess.py:93} INFO - üìä Creating chart: Average Transaction Amount by Age Group
[2025-05-23T09:04:08.757+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Average Transaction Amount by Age Group' created (ID: 21)
[2025-05-23T09:04:08.757+0000] {subprocess.py:93} INFO - üìä Creating chart: Distribution of Payment Methods
[2025-05-23T09:04:08.758+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Distribution of Payment Methods' created (ID: 22)
[2025-05-23T09:04:08.758+0000] {subprocess.py:93} INFO - üìä Creating chart: Transaction Volume by Device Type
[2025-05-23T09:04:08.758+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Transaction Volume by Device Type' created (ID: 23)
[2025-05-23T09:04:08.759+0000] {subprocess.py:93} INFO - üìä Creating chart: Revenue by Product Category
[2025-05-23T09:04:08.759+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Revenue by Product Category' created (ID: 24)
[2025-05-23T09:04:08.759+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:04:08.759+0000] {subprocess.py:93} INFO - üìà Successfully created 6 out of 6 charts
[2025-05-23T09:04:08.851+0000] {subprocess.py:93} INFO - python: can't open file '/app/step4_create_dashbord.py': [Errno 2] No such file or directory
[2025-05-23T09:04:08.861+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-23T09:04:08.871+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-23T09:04:08.874+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_superset_dashboard, execution_date=20250523T085747, start_date=20250523T090400, end_date=20250523T090408
[2025-05-23T09:04:08.888+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 54 for task run_superset_dashboard (Bash command failed. The command returned a non-zero exit code 2.; 13381)
[2025-05-23T09:04:08.937+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-23T09:04:08.959+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
