[2025-05-09T17:43:50.567+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_all_three_commands manual__2025-05-09T17:38:07.153488+00:00 [queued]>
[2025-05-09T17:43:50.582+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_all_three_commands manual__2025-05-09T17:38:07.153488+00:00 [queued]>
[2025-05-09T17:43:50.582+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-09T17:43:50.607+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_all_three_commands> on 2025-05-09 17:38:07.153488+00:00
[2025-05-09T17:43:50.614+0000] {standard_task_runner.py:57} INFO - Started process 4306 to run task
[2025-05-09T17:43:50.621+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_all_three_commands', 'manual__2025-05-09T17:38:07.153488+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmpx2e2t3js']
[2025-05-09T17:43:50.627+0000] {standard_task_runner.py:85} INFO - Job 77: Subtask run_all_three_commands
[2025-05-09T17:43:50.710+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_all_three_commands manual__2025-05-09T17:38:07.153488+00:00 [running]> on host d4afc872a8aa
[2025-05-09T17:43:50.825+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_all_three_commands' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T17:38:07.153488+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T17:38:07.153488+00:00'
[2025-05-09T17:43:50.827+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-09T17:43:50.830+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'command1 && command2 && command3']
[2025-05-09T17:43:50.841+0000] {subprocess.py:86} INFO - Output:
[2025-05-09T17:43:50.843+0000] {subprocess.py:93} INFO - /bin/bash: line 1: command1: command not found
[2025-05-09T17:43:50.844+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-09T17:43:50.856+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-09T17:43:50.861+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_all_three_commands, execution_date=20250509T173807, start_date=20250509T174350, end_date=20250509T174350
[2025-05-09T17:43:50.880+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 77 for task run_all_three_commands (Bash command failed. The command returned a non-zero exit code 127.; 4306)
[2025-05-09T17:43:50.912+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-09T17:43:50.929+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
