[2025-05-09T15:57:11.540+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.update_hql_file manual__2025-05-09T15:50:51.637660+00:00 [queued]>
[2025-05-09T15:57:11.551+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.update_hql_file manual__2025-05-09T15:50:51.637660+00:00 [queued]>
[2025-05-09T15:57:11.552+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2025-05-09T15:57:11.568+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): update_hql_file> on 2025-05-09 15:50:51.637660+00:00
[2025-05-09T15:57:11.576+0000] {standard_task_runner.py:57} INFO - Started process 1872 to run task
[2025-05-09T15:57:11.579+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'update_hql_file', 'manual__2025-05-09T15:50:51.637660+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmpctx2x3iv']
[2025-05-09T15:57:11.583+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask update_hql_file
[2025-05-09T15:57:11.641+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.update_hql_file manual__2025-05-09T15:50:51.637660+00:00 [running]> on host d4afc872a8aa
[2025-05-09T15:57:11.733+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='update_hql_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T15:50:51.637660+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T15:50:51.637660+00:00'
[2025-05-09T15:57:11.742+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-05-09T15:57:11.743+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingestion.py", line 59, in update_hql_file
    with tempfile.NamedTemporaryFile(delete=False, suffix='.hql') as temp_file:
NameError: name 'tempfile' is not defined
[2025-05-09T15:57:11.761+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=update_hql_file, execution_date=20250509T155051, start_date=20250509T155711, end_date=20250509T155711
[2025-05-09T15:57:11.774+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task update_hql_file (name 'tempfile' is not defined; 1872)
[2025-05-09T15:57:11.794+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-09T15:57:11.819+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
