[2025-05-09T16:32:06.265+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T16:26:34.168864+00:00 [queued]>
[2025-05-09T16:32:06.275+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T16:26:34.168864+00:00 [queued]>
[2025-05-09T16:32:06.276+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-09T16:32:06.291+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_hive_command> on 2025-05-09 16:26:34.168864+00:00
[2025-05-09T16:32:06.297+0000] {standard_task_runner.py:57} INFO - Started process 3093 to run task
[2025-05-09T16:32:06.300+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_hive_command', 'manual__2025-05-09T16:26:34.168864+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmp9dtzwyho']
[2025-05-09T16:32:06.302+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask run_hive_command
[2025-05-09T16:32:06.346+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T16:26:34.168864+00:00 [running]> on host d4afc872a8aa
[2025-05-09T16:32:06.424+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_hive_command' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T16:26:34.168864+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T16:26:34.168864+00:00'
[2025-05-09T16:32:06.426+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-09T16:32:06.427+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec hive hive -f query.hql']
[2025-05-09T16:32:06.438+0000] {subprocess.py:86} INFO - Output:
[2025-05-09T16:32:06.468+0000] {subprocess.py:93} INFO - Error response from daemon: container a4afb1d294c38981da646ca74b16a3130248d4354fc4cfa57941a60d460b64bb is not running
[2025-05-09T16:32:06.470+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-09T16:32:06.479+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-09T16:32:06.482+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_hive_command, execution_date=20250509T162634, start_date=20250509T163206, end_date=20250509T163206
[2025-05-09T16:32:06.495+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 61 for task run_hive_command (Bash command failed. The command returned a non-zero exit code 1.; 3093)
[2025-05-09T16:32:06.514+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-09T16:32:06.535+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
