[2025-05-23T09:28:09.232+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard manual__2025-05-23T09:27:00.223067+00:00 [queued]>
[2025-05-23T09:28:09.262+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard manual__2025-05-23T09:27:00.223067+00:00 [queued]>
[2025-05-23T09:28:09.264+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-23T09:28:09.297+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_superset_dashboard> on 2025-05-23 09:27:00.223067+00:00
[2025-05-23T09:28:09.308+0000] {standard_task_runner.py:57} INFO - Started process 606 to run task
[2025-05-23T09:28:09.314+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_superset_dashboard', 'manual__2025-05-23T09:27:00.223067+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp__4ynbt_']
[2025-05-23T09:28:09.320+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask run_superset_dashboard
[2025-05-23T09:28:09.446+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_superset_dashboard manual__2025-05-23T09:27:00.223067+00:00 [running]> on host 6c702459c558
[2025-05-23T09:28:10.023+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_superset_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T09:27:00.223067+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-23T09:27:00.223067+00:00'
[2025-05-23T09:28:10.037+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-23T09:28:10.039+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec superset python /app/dashboard/step1_connection_db.py && docker exec superset python /app/dashboard/step2_creation_of_datasets.py && docker exec superset python /app/dashboard/step3_create_charts.py && docker exec superset python step4_create_dashbord.py']
[2025-05-23T09:28:10.082+0000] {subprocess.py:86} INFO - Output:
[2025-05-23T09:28:16.882+0000] {subprocess.py:93} INFO - ‚úÖ Login successful.
[2025-05-23T09:28:16.883+0000] {subprocess.py:93} INFO - Access Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNzQ3OTkyNDkxLCJqdGkiOiI4M2YxYmQ4Yy0zYjUyLTRlODctYmU3ZC0zOGRkOGUzMTczOWMiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE3NDc5OTI0OTEsImNzcmYiOiI4ODZmZjdjMS00ZTllLTRmZjgtOTY5OS1hMjg2ODVkNDYzNjkiLCJleHAiOjE3NDc5OTMzOTF9.EQSn0N7d51WHrCvdqW0BR9zNvrRBtw3xgYaDHRAAg64
[2025-05-23T09:28:16.883+0000] {subprocess.py:93} INFO - ‚úÖ CSRF token received:
[2025-05-23T09:28:16.883+0000] {subprocess.py:93} INFO - ImJmNjI4NzZlYmJkNjZiNjU3MmY3YjliZjQ2ODg0ZDE3NWYxY2JhNWIi.aDA_qw.mNyKOrZzipa6PnU__MlJ70nnYaA
[2025-05-23T09:28:16.884+0000] {subprocess.py:93} INFO - Status: 422
[2025-05-23T09:28:16.884+0000] {subprocess.py:93} INFO - Response: {"message":"Database could not be created."}
[2025-05-23T09:28:16.884+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:29:47.256+0000] {subprocess.py:93} INFO - ‚úÖ Logged in successfully
[2025-05-23T09:29:47.258+0000] {subprocess.py:93} INFO - ‚úÖ CSRF token retrieved
[2025-05-23T09:29:47.260+0000] {subprocess.py:93} INFO - ‚úÖ Hive Warehouse database ID: 1
[2025-05-23T09:29:47.260+0000] {subprocess.py:93} INFO - ‚úÖ Dataset 'Distribution of Payment Methods' created successfully. ID: 1
[2025-05-23T09:29:47.261+0000] {subprocess.py:93} INFO - ‚úÖ Dataset 'Transaction Volume by Device Type' created successfully. ID: 2
[2025-05-23T09:29:47.262+0000] {subprocess.py:93} INFO - ‚úÖ Dataset 'Average Transaction Amount by Customer Age Group' created successfully. ID: 3
[2025-05-23T09:29:47.263+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":"Fatal error"}
[2025-05-23T09:29:47.264+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:29:47.265+0000] {subprocess.py:93} INFO - Status: 500
[2025-05-23T09:29:47.266+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":"Fatal error"}
[2025-05-23T09:29:47.266+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:29:47.267+0000] {subprocess.py:93} INFO - Status: 500
[2025-05-23T09:29:47.268+0000] {subprocess.py:93} INFO - ‚ùå Failed to create dataset: {"message":"Fatal error"}
[2025-05-23T09:29:47.269+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:29:47.269+0000] {subprocess.py:93} INFO - Status: 500
[2025-05-23T09:30:06.038+0000] {subprocess.py:93} INFO - üîê Authenticating with Superset...
[2025-05-23T09:30:06.039+0000] {subprocess.py:93} INFO - ‚úÖ Authentication successful
[2025-05-23T09:30:06.039+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:30:06.040+0000] {subprocess.py:93} INFO - üöÄ Starting dashboard creation process...
[2025-05-23T09:30:06.040+0000] {subprocess.py:93} INFO - üìä Charts to create: 6
[2025-05-23T09:30:06.040+0000] {subprocess.py:93} INFO - üèóÔ∏è Dashboard name: Transaction Analytics Dashboard
[2025-05-23T09:30:06.041+0000] {subprocess.py:93} INFO - ==================================================
[2025-05-23T09:30:06.041+0000] {subprocess.py:93} INFO - üìä Creating chart: Fraud Detection Overview
[2025-05-23T09:30:06.041+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Fraud Detection Overview' created (ID: 2)
[2025-05-23T09:30:06.041+0000] {subprocess.py:93} INFO - üìä Creating chart: Number of Transactions by Month
[2025-05-23T09:30:06.042+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Number of Transactions by Month' created (ID: 5)
[2025-05-23T09:30:06.042+0000] {subprocess.py:93} INFO - üìä Creating chart: Average Transaction Amount by Age Group
[2025-05-23T09:30:06.042+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Average Transaction Amount by Age Group' created (ID: 8)
[2025-05-23T09:30:06.043+0000] {subprocess.py:93} INFO - üìä Creating chart: Distribution of Payment Methods
[2025-05-23T09:30:06.043+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Distribution of Payment Methods' created (ID: 10)
[2025-05-23T09:30:06.043+0000] {subprocess.py:93} INFO - üìä Creating chart: Transaction Volume by Device Type
[2025-05-23T09:30:06.043+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Transaction Volume by Device Type' created (ID: 12)
[2025-05-23T09:30:06.044+0000] {subprocess.py:93} INFO - üìä Creating chart: Revenue by Product Category
[2025-05-23T09:30:06.044+0000] {subprocess.py:93} INFO - ‚úÖ Chart 'Revenue by Product Category' created (ID: 14)
[2025-05-23T09:30:06.044+0000] {subprocess.py:93} INFO - 
[2025-05-23T09:30:06.044+0000] {subprocess.py:93} INFO - üìà Successfully created 6 out of 6 charts
[2025-05-23T09:30:06.135+0000] {subprocess.py:93} INFO - python: can't open file '/app/step4_create_dashbord.py': [Errno 2] No such file or directory
[2025-05-23T09:30:06.145+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-23T09:30:06.156+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-23T09:30:06.161+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_superset_dashboard, execution_date=20250523T092700, start_date=20250523T092809, end_date=20250523T093006
[2025-05-23T09:30:06.176+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task run_superset_dashboard (Bash command failed. The command returned a non-zero exit code 2.; 606)
[2025-05-23T09:30:06.195+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-23T09:30:06.218+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
