[2025-05-09T16:15:40.890+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T16:09:19.498929+00:00 [queued]>
[2025-05-09T16:15:40.904+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T16:09:19.498929+00:00 [queued]>
[2025-05-09T16:15:40.905+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-09T16:15:40.922+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_hive_command> on 2025-05-09 16:09:19.498929+00:00
[2025-05-09T16:15:40.929+0000] {standard_task_runner.py:57} INFO - Started process 2543 to run task
[2025-05-09T16:15:40.932+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_hive_command', 'manual__2025-05-09T16:09:19.498929+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmpt0b5lt2a']
[2025-05-09T16:15:40.937+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask run_hive_command
[2025-05-09T16:15:40.993+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_hive_command manual__2025-05-09T16:09:19.498929+00:00 [running]> on host d4afc872a8aa
[2025-05-09T16:15:41.080+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_hive_command' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T16:09:19.498929+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T16:09:19.498929+00:00'
[2025-05-09T16:15:41.082+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-09T16:15:41.085+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec hive hive -f query.hql']
[2025-05-09T16:15:41.099+0000] {subprocess.py:86} INFO - Output:
[2025-05-09T16:15:42.769+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-05-09T16:15:42.770+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-05-09T16:15:42.770+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.4/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-05-09T16:15:42.771+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-05-09T16:15:42.771+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-05-09T16:15:43.919+0000] {subprocess.py:93} INFO - 
[2025-05-09T16:15:43.920+0000] {subprocess.py:93} INFO - Logging initialized using configuration in file:/opt/hive/conf/hive-log4j2.properties Async: true
[2025-05-09T16:16:12.466+0000] {subprocess.py:93} INFO - FAILED: SemanticException org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
[2025-05-09T16:17:00.998+0000] {subprocess.py:97} INFO - Command exited with return code 64
[2025-05-09T16:17:01.010+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 64.
[2025-05-09T16:17:01.015+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_hive_command, execution_date=20250509T160919, start_date=20250509T161540, end_date=20250509T161701
[2025-05-09T16:17:01.033+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task run_hive_command (Bash command failed. The command returned a non-zero exit code 64.; 2543)
[2025-05-09T16:17:01.055+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-09T16:17:01.076+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
